require:
  - rubocop
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1.6
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'log/**/*'
    - 'tmp/**/*'

Metrics/BlockLength:
  Exclude:
    - "config/**/*"
    - "spec/**/*"
    - "lib/tasks/**/*"
  Max: 120

Metrics/ClassLength:
  Max: 120
  
Metrics/MethodLength:
  Max: 20

Style/Documentation:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

Layout/LineLength:
  Exclude:
    - "config/**/*"

DescribeClass:
  Exclude:
    - "spec/tasks/*"

MultipleMemoizedHelpers:
  Exclude:
    - "spec/**/*"

LetSetup:
  Exclude:
    - "spec/**/*"

RSpec/EmptyExampleGroup:
  Enabled: false

RSpec/ScatteredSetup:
  Enabled: false

Lint/SuppressedException:
  Exclude:
    - "lib/authorize_api_request.rb"

RSpec/ContextWording:
  Prefixes:
    - when
    - with
    - without
    - and
