version: 2
jobs:
  build:
    working_directory: ~/your-app-name
    docker:
      - image: circleci/ruby:3.1.2
        environment:
          PGHOST: localhost
          PGUSER: postgres
          RAILS_ENV: test

      - image: postgres:9.5
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: DB_TEST
          POSTGRES_PASSWORD: password
    steps:
      - checkout

      - type: cache-restore
        name: Restore bundle cache
        key: your-app-name-{{ checksum "Gemfile.lock" }}

      - run: bundle install --path vendor/bundle

      - type: cache-save
        name: Store bundle cache
        key: your-app-name-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      - run: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run: cp .sample.env .env

      - run: bundle exec rake db:setup

      - run: bundle exec rake
