default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *default
  database: <%= ENV['DB_DEVELOPMENT'] %>

test:
  <<: *default
  database: <%= ENV['DB_TEST'] %>

production:
  <<: *default
  database: <%= ENV['DB_PRODUCTION'] %>
